# Generated by Django 3.0.1 on 2020-01-10 07:42

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Addblog',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=100)),
                ('blog', models.CharField(max_length=1000)),
                ('date', models.DateField(default=datetime.datetime(2020, 1, 10, 13, 12, 14, 725234))),
            ],
        ),
    ]
