# Generated by Django 3.0.1 on 2020-01-24 06:38

import datetime
from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0002_auto_20200109_1202'),
        ('blog', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='addblog',
            name='author',
            field=models.ForeignKey(default=django.utils.timezone.now, on_delete=django.db.models.deletion.CASCADE, to='users.AddUser'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='addblog',
            name='date',
            field=models.DateField(default=datetime.datetime(2020, 1, 24, 12, 7, 49, 733746)),
        ),
    ]
