# Generated by Django 3.0.1 on 2020-01-24 06:42

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0002_auto_20200124_1208'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Addblog',
        ),
    ]
