# Generated by Django 3.0.1 on 2020-01-24 06:47

import datetime
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('users', '0002_auto_20200109_1202'),
        ('blog', '0003_delete_addblog'),
    ]

    operations = [
        migrations.CreateModel(
            name='Addblog',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=100)),
                ('blog', models.CharField(max_length=1000)),
                ('date', models.DateField(default=datetime.datetime(2020, 1, 24, 12, 17, 39, 317504))),
                ('author', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='users.AddUser')),
            ],
        ),
    ]
