# Generated by Django 3.0.1 on 2020-01-24 06:48

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0004_addblog'),
    ]

    operations = [
        migrations.AlterField(
            model_name='addblog',
            name='date',
            field=models.DateField(default=datetime.datetime(2020, 1, 24, 12, 18, 45, 162738)),
        ),
    ]
