# Generated by Django 3.0.1 on 2020-01-09 06:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='adduser',
            name='pic',
            field=models.ImageField(upload_to='static/images'),
        ),
    ]
